### ISSUE TITLE
help~

### ISSUE THREAD

**Issue by xzx198899** [parai/as#1]
---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,2)

when I run ./run.sh in aslinux/build, I find this problem, could you help me? thank you

**Comment by parai** [comment]
is the log of arm qemu ?

**Comment by xzx198899** [comment]
Now I am trying to make sdcard, but failed, here are the logs: 
make sdcard
Error: The device /home/xzx/as-master/release/aslinux/build/out/sdcard.img is so
small that it cannot possibly store a file system or partition table.  Perhaps
you selected the wrong device?
Failed to read bootsector (size=0)                                        
Failed to mount '/dev/loop0': Invalid argument

Did I miss some steps? or I should make aslua first?
I tryed to build aslua, still failed when built websock,  here are logs:
whether we are cross compiling... configure: error: in `/home/xzx/as-master/release/download/libmicrohttpd-0.9.55':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.

**Comment by xzx198899** [comment]
@parai

**Comment by parai** [comment]
you really  need to get support from google to learn what does command " dd/fdisk/parted" and then get back to see the code logic of the make sdcard part of the Makefile, on my side, no such issue, you should help yourself to resolve the probelm, here I suggest you to try delete the sdcard.img and try again.

**Comment by rex1095x** [comment]
when compiling in scons, it report error as below: 
 **CC fnmatch.o
fnmatch.c:1:1: error: expected identifier or '(' before numeric constant
    1 | 404: Not Found
      | ^~~
make: *** [Makefile:329: fnmatch.o] Error 1
Exception: FAIL of RunCommand "cd E:\030_Programs\Repos\as_master\as\/release/download/dtc & sed -i "s/p_fnmatch(/fnmatch(/g" fnmatch.c & sed -i "s/FNM_NOSYS/2/g" fnmatch.c & sed -i "s/FNM_NORES/3/g" fnmatch.c & sed -i "s/git__tolower/tolower/g" fnmatch.c & sed -i "s/lstat/stat/g" fstree.c & make" = 2:**

so I checked the  fnmatch.c in "as\release\download\dtc", and there is no code in the file:
fnmatch.h: <a href="/git-for-windows/msys2-runtime/master/include/fnmatch.h">Moved Permanently</a>.
fnmatch.c: 404: Not Found
how to fix this problem? thanks for your help and looking forward to hearing from you !
