### ISSUE TITLE
update newer source asone compile error

### ISSUE THREAD

**Issue by yifengling0** [parai/as#11]
make[1]: Leaving directory '/c/Users/liufe/Documents/GitHub/as/release/aslua'
make[1]: Entering directory '/c/Users/liufe/Documents/GitHub/as/release/aslua/out'
g++ -c -O2 -Wall -D_hypot=hypot -DNDEBUG -DUNICODE -DQT_LARGEFILE_SUPPORT -I. -IC:/Anaconda3/include -o sipAScmodule.o sipAScmodule.cpp
In file included from C:/Anaconda3/include/Python.h:50:0,
                 from C:/Anaconda3/include/sip.h:32,
                 from sipAPIAS.h:11,
                 from sipAScmodule.cpp:7:
C:/Anaconda3/include/pyport.h:686:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

**Comment by parai** [comment]
have you find the way to fix it, on my side, no such issues

**Comment by yifengling0** [comment]
use mingw64/bin instead msys2 gcc/g++ will fix this problem.
