### ISSUE TITLE
Install on Linux

### ISSUE THREAD

**Issue by inquisitor93** [parai/as#12]
Hi,

thank you for your work! Is there any clear tutorial on how to build everything on Linux available? 

I was starting building ascore with make and I get this error: No module named 'BSWCOM'. What else do I have to build to get started?

**Comment by parai** [comment]
you can check on this http://parai.github.io/as/autosar/2018/02/20/as-study-platform.html

**Comment by parai** [comment]
@Karagoz4 : that console.bat is for windows, not for ubuntu, you can use ubuntu terminal directly to build as
