### ISSUE TITLE
.config 文件怎么配置？

### ISSUE THREAD

**Issue by jingr1** [parai/as#14]
根据http://parai.github.io/as/autosar/2018/02/20/as-study-platform.html搭建环境.
运行scons --menuconfig 的时候报错
![image](https://user-images.githubusercontent.com/7448804/49056359-6c10db80-f236-11e8-8a12-8a9354963c72.png)

查到这一步GetConfig('.config',env)

添加.config 空文件后这一步过了
![image](https://user-images.githubusercontent.com/7448804/49056139-5353f600-f235-11e8-8b8e-adc884059bfa.png)
但又报了如下问题
  File "/d/BuildArea/AS/as/com/as.infrastructure/system/kernel/SConscript", line 43:
    assert(0)

查看代码应该是.config 没有配好 MODULES没有找到
不知道是不是这个原因？请大神指点。

**Comment by parai** [comment]
你就不要menuconfig，直接默认编译，把.config删掉，等你把AS都搞清楚了在玩menuconfig
