### ISSUE TITLE
qemu 闪退

### ISSUE THREAD

**Issue by jingr1** [parai/as#15]
我的qemu编译安装完之后，运行 scons run , cmd 黑框闪了一下就没有了，qemu 没有启动。
telnet 连不上， 大神有什么好的建议吗？

我下载了一个windows版本qemu，可以运行并打印消息，然后停在下图的界面不动了
不知道停在了什么地方？
qemu 没有显示。

![Uploading image.png…]()

**Comment by parai** [comment]
scons run --verbose
you can see the command which launch the qemu, then run that command in another window run that command, and then in another command do run command telnet to check what is wrong,

Generally I think the qemu hit the assert of ascan/asnet/asblk.

**Comment by jingr1** [comment]
1. for the qemu compiled according the flow your given.
I can see the command run as below
![image](https://user-images.githubusercontent.com/7448804/49917029-6ffc5900-fed8-11e8-8388-ae8672a08093.png)
and I run the command 
"cd D:\Tools\as\/release/ascore && start cmd /C C:\msys64/mingw64/bin//qemu-system-arm.exe -m 128 -M versatilepb -kernel D:\Tools\as\/release/ascore/versatilepb.exe -serial tcp:127.0.0.1:1103,server -device pci-ascan -device pci-asnet -device pci-asblk"
telenet can't connected.
I think the problem is qemu don't be launched, I don;t know why?
2. for the windows version qemu I download, it can be launched, but don't include  ascan/asnet/asblk.
so it can't run well. do you know how to add ascan/asnet/asblk int the windows version qemu?

**Comment by parai** [comment]
you should remove the "start cmd /C", and try again

**Comment by jingr1** [comment]
NO helpful
![image](https://user-images.githubusercontent.com/7448804/49979781-8dd6c600-ff8b-11e8-8bfe-61dff836a706.png)

**Comment by parai** [comment]
just "C:\msys64/mingw64/bin//qemu-system-arm.exe -m 128 -M versatilepb -kernel D:\Tools\as/release/ascore/versatilepb.exe -serial tcp:127.0.0.1:1103,server -device pci-ascan -device pci-asnet -device pci-asblk"

remove the "Cd part"

**Comment by parai** [comment]
sounds strange, can you try the [asenv.zip](https://pan.baidu.com/s/1NNNiSBCyYsdsvSknBKe3JQ) which has a qemu inside built by me.
