### ISSUE TITLE
Compile error in ascan.c

### ISSUE THREAD

**Issue by geynis** [parai/as#16]
ascan.c:415: undefined reference to `luai_canlib_close'
doesn't it need to include "lascanlib.h"?
![image](https://user-images.githubusercontent.com/2669527/50205967-ac193900-0372-11e9-8e39-aee7cc937c3e.png)

**Comment by parai** [comment]
Hi:
thanks for the error report, it's maybe because of the aslua Makefile update, but I forgot to update the PKGBUILD.

please try update  code to below commit and try build again.
https://github.com/parai/as/commit/dbe32b7aeea4617c1edf74d4f4cfdc6b06f69cec
