### ISSUE TITLE
about msys2

### ISSUE THREAD

**Issue by lihaibin001** [parai/as#3]
My msys2 is MSYS_NT-6.1,  Can  it work? And where can i download the MSYS_NT-10.0?

**Comment by parai** [comment]
just try, maybe it's okay.

**Comment by lihaibin001** [comment]
but, I can not build it, it print like these: help me! thank you.
g++ -c -O2 -Wall -D_hypot=hypot -DNDEBUG -DUNICODE -DQT_LARGEFILE_SUPPORT -I. -IC:/Anaconda3/include -o sipAScmodule.o sipAScmodule.cpp
g++ -c -O2 -Wall -D_hypot=hypot -DNDEBUG -DUNICODE -DQT_LARGEFILE_SUPPORT -I. -IC:/Anaconda3/include -o sipASasdev.o sipASasdev.cpp
g++ -c -O2 -Wall -D_hypot=hypot -DNDEBUG -DUNICODE -DQT_LARGEFILE_SUPPORT -I. -IC:/Anaconda3/include -o sipAScan.o sipAScan.cpp
g++ -mthreads -Wl,-enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-reloc -shared -Wl,-subsystem,windows -Wl,-s -o AS.pyd sipAScmodule.o sipASasdev.o sipAScan.o -LD:/study/autosar/as-master/as-master/release/aslua/out C:/Anaconda3/libs/python36.lib -lpyas -laws -lpyas -lpthread -lm -lPCANBasic -lwsock32 -lZLGCAN C:/Anaconda3/python36.dll
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(json_util.o): In function `NtCurrentTeb':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8603: multiple definition of `NtCurrentTeb'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8603: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(json_util.o): In function `GetCurrentFiber':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8604: multiple definition of `GetCurrentFiber'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8604: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(json_util.o): In function `GetFiberData':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8605: multiple definition of `GetFiberData'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8605: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(linkhash.o): In function `NtCurrentTeb':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8603: multiple definition of `NtCurrentTeb'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8603: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(linkhash.o): In function `GetCurrentFiber':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8604: multiple definition of `GetCurrentFiber'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8604: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(linkhash.o): In function `GetFiberData':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8605: multiple definition of `GetFiberData'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8605: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(random_seed.o): In function `NtCurrentTeb':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8603: multiple definition of `NtCurrentTeb'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8603: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(random_seed.o): In function `GetCurrentFiber':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8604: multiple definition of `GetCurrentFiber'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8604: first defined here
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(random_seed.o): In function `GetFiberData':
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8605: multiple definition of `GetFiberData'
D:/study/autosar/as-master/as-master/release/aslua/out/libaws.a(asocket.o):C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:8605: first defined here
collect2.exe: error: ld returned 1 exit status

**Comment by parai** [comment]
check  as.tool/lua/device/websock/Makefile
35$(warning need modify the /c/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h line 2100/8474, \
36    add "FORCEINLINE" to each of the inline function)

Please note the waning message at the begining of the log, you should modify some of msys file by hand, that is msys issue.
