### ISSUE TITLE
无法用英文表达，其实不是一个bug，而是工具链的问题，自己无能为力

### ISSUE THREAD

**Issue by geekyes** [parai/as#4]
本小白的系统环境：win7_32bit + msys32
前提：自己的学习方法是先把工具链跑起来，然后再去看具体的代码（所以对工程的了解程度有限制）

![2](https://user-images.githubusercontent.com/31738262/37237005-afe92d10-2448-11e8-9e63-772ea1369185.png)
这个构建错误是因为scons检测到是win系统，所以在命令行编译命令的参数是"/"加编译参数，例如定义宏定义，就是`/DDEFINE`，但是arm-none-eabi-gcc的是`-DDEFINE`。我自己也尝试的写了一个scons的脚本，编译一个简单的单文件程序，代码如下：
![4](https://user-images.githubusercontent.com/31738262/37237143-c6d7a8d8-244a-11e8-9c90-278048767755.png)
分别在win7的cmd(右边)和msys2的bash(左边)下执行scons脚本，结果如下：
![5](https://user-images.githubusercontent.com/31738262/37237181-1c689c58-244b-11e8-84c0-22c8fabdd9ec.png)
说明scons在sys.platform = msys时，可以给arm-none-eabi-gcc能识别的编译参数格式，但是在sys.platform = msys时，building.py会抛出异常。
总结下：主要的问题就是scons在根据平台生成编译命令是，参数的生成格式不正确，结果如第一张图片。
自己的想法：既然大大（parai）能在win10下编译成功，说明这一步是肯定遇到的，所以前来提问。

**Comment by parai** [comment]
这是一个scons 不支持msys2的问题，没啥好折腾的， 请安装MINGW即可解决该问题。
可以参考此文搭建开发环境：http://parai.github.io/as/autosar/2018/02/20/as-study-platform.html
