### ISSUE TITLE
"sys/queue.h No such file or directory" while generating socketwin_can_driver.exe

### ISSUE THREAD

**Issue by alwang121212** [parai/as#5]
Whenever I ran the command "scons run", It always shows below error message.
 >> RunCommand "gcc -D__SOCKET_WIN_CAN_DRIVER__ C:\Users\Hommer\as/com/as.tool/lua/can/socketwin_can_driver.c -lwsock32 -o C:\Users\Hommer\as/com/as.tool/lua/script/socketwin_can_driver.exe"
C:\Users\Hommer\as/com/as.tool/lua/can/socketwin_can_driver.c:18:10: fatal error: sys/queue.h: No such file or directory
 #include <sys/queue.h>
          ^~~~~~~~~~~~~
compilation terminated.

Which _queue.h_ file supposed to be used here?
Did I miss any packages that should be installed first?

**Comment by parai** [comment]
you should copy this one https://github.com/parai/as/blob/master/com/as.infrastructure/include/sys/queue.h to msys include directory, and generally should add cflags as below:
-I${ASROOT}/com/as.infrastructure/include/

**Comment by parai** [comment]
fixed with commit 6866af33f7bea097f92dc863d37e9e2e2b072d99, thanks for the report

**Comment by alwang121212** [comment]
Hi Parai
These error messages came from _as\com\as.tool\config.infrastructure.system\building.py_
At line 556 : _cmd = '%s -D__SOCKET_WIN_CAN_DRIVER__ %s -lwsock32 -o %s'%(Env['CC'], candrvsrc, candrvtgt)_

I think _-I${ASROOT}/com/as.infrastructure/include/_ should be added here.

**Comment by parai** [comment]
already done, please update your code
