### ISSUE TITLE
kconfig-mconf.exe excutes failed

### ISSUE THREAD

**Issue by dsn0327** [parai/as#6]
I got this:
source "$ASROOT/com/as.infrastructure/system/kernel/rtthread/rt-thread/Kconfig"
 failed, there is no ”rt-thread/Kconfig“  in directory of "as/com/as.infrastructure/system/kernel/rtthread"

**Comment by parai** [comment]
on which commit id?
and lastest version of as has no support of rtthread now. try fix this issue by yourself maybe.

**Comment by dsn0327** [comment]
it is the newest one. ok, i skip it.
I have another problem, there is the console prints:
scons: done reading SConscript files.
scons: Building targets ...
CC app/app.c
Error in calling:
/f/work/as/release/download/gcc-arm-none-eabi-5_4-2016q3-20160926-win32/bin/arm-none-eabi-gcc -std=gnu99 -o "build/versatilepb/app/app.o" -c -O0 -g -mcpu=arm926ej-s -marm -ffunction-sections -fdata-sections -I/f/work/as/release/ascore/SgDesign/SgRes --include build/versatilepb/config/asmconfig.h -DconfigTOTAL_HEAP_SIZE=0x800000 -DMEMORY_SIZE=0x8000000 -DSYSTEM_REGION_START=0x10000000 -DSYSTEM_REGION_END=0x101f4000 -DPAGE_SIZE=0x1000 -DOS_TICKS_PER_SECOND=100 -DUSECONDS_PER_TICK=10000 -DOS_STK_SIZE_SCALER=4 -DCAN_LL_DL=64 -DUSE_PCAPIF -DUSE_PROTOTHREAD -DUSE_GUI -DFTPD_DEBUG -DCONFIG_USE_DEFAULT_CFG -DCONFIG_HAVE_OWN_OFLAGS=0 -I/f/work/as/com/as.application/board.posix/common -I/f/work/as/com/as.application/common/config -I/f/work/as/com/as.infrastructure/include -I/f/work/as/com/as.infrastructure/arch/versatilepb/bsp -I/f/work/as/com/as.infrastructure/arch/versatilepb/mcal -I/f/work/as/com/as.infrastructure/arch/common/lwip -I/f/work/as/com/as.infrastructure/communication/CanTp -I/f/work/as/com/as.infrastructure/communication/Com -I/f/work/as/com/as.infrastructure/communication/ComM -I/f/work/as/com/as.infrastructure/communication/DoIP -I/f/work/as/com/as.infrastructure/communication/Nm -I/f/work/as/com/as.infrastructure/communication/OsekNm -I/f/work/as/com/as.infrastructure/communication/Pci -I/f/work/as/com/as.infrastructure/communication/PduR -I/f/work/as/com/as.infrastructure/communication/SoAd -I/f/work/as/com/as.infrastructure/communication/Xcp -I/f/work/as/com/as.infrastructure/communication/J1939Tp -I/f/work/as/com/as.infrastructure/diagnostic/Dcm -I/f/work/as/com/as.infrastructure/memory/Ea -I/f/work/as/com/as.infrastructure/system/kernel -I/f/work/as/com/as.infrastructure/system/kernel/askar/include -I/f/work/as/com/as.infrastructure/system/kernel/askar/kernel -I/f/work/as/com/as.infrastructure/system/kernel/askar/portable/arm -I/f/work/as/release/download/contiki/core -I/f/work/as/com/as.infrastructure/system/kernel/contiki/include -I/f/work/as/com/as.infrastructure/system/kernel/contiki/platform/native -I/f/work/as/com/as.infrastructure/system/EcuM -I/f/work/as/com/as.infrastructure/system/SchM -I/f/work/as/com/as.infrastructure/system/gui -I/f/work/as/com/as.infrastructure/system/net/lwip/lwip/src/include -I/f/work/as/com/as.infrastructure/system/net/lwip/lwip/src/include/ipv4 -I/f/work/as/com/as.infrastructure/system/net/ftp -I/f/work/as/com/as.infrastructure/system/fs/fatfs/fatfs/source -I/f/work/as/com/as.infrastructure/system/fs/lwext4/lwext4/include -I/f/work/as/com/as.infrastructure/system/fs/libelf/include -I/f/work/as/com/as.infrastructure/system/fs/libelf -I/f/work/as/com/as.infrastructure/system/fs/vfs -I/f/work/as/com/as.infrastructure/system/fs/libdl -Ibuild/versatilepb/config -I/f/work/as/com/config "app/app.c"
Exception: [Errno 2] No such file or directory: No such file or directory
scons: *** [build/versatilepb/app/app.o] Error 2
scons: building terminated because of errors.
i do not know why there are quotations on app/app.c and app/app.o

**Comment by parai** [comment]
are you type scons command in the console.bat, don't use msys2 shell?

**Comment by dsn0327** [comment]
in console.bat there is problem too. there is prints:
Microsoft Windows [版本 10.0.16299.371]
(c) 2017 Microsoft Corporation。保留所有权利。

F:\work\as\release\ascore>scons
scons: Reading SConscript files ...
('Modules:', ['PLATFORM_MSYS2', 'ARCH_VERSATILEPB', 'TEST', 'PCI', 'CAN', 'FATFS_DRV', 'LWEXT4_DRV', 'EEP', 'FLS', 'LCD', 'MCU', 'LWIP_DRV', 'CANIF', 'CANNM', 'CANSM', 'CANTP', 'COM', 'COMM', 'DOIP', 'NM', 'OSEKNM', 'PDUR', 'SOAD', 'XCP', 'J1939TP', 'DCM', 'DEM', 'DET', 'EA', 'FEE', 'MEMIF', 'NVM', 'CRC', 'ECUM', 'SG', 'SCHM', 'SHELL', 'FATFS', 'LWEXT4', 'VFS', 'LIBELF', 'LIBDL', 'DEFAULT_ASKAR', 'ASKAR', 'PROTOTHREAD', 'SCHED_BUBBLE', 'PTHREAD', 'PTHREAD_SIGNAL', 'PTHREAD_CLEANUP', 'LWIP', 'LWIP_OSEK_ARCH', 'FTP', 'CLIB_ASHEAP', 'CLIB_MBOX', 'CLIB_MISCLIB',
'CLIB_QSORT', 'CLIB_STDIO_PRINTF', 'CLIB_STDIO_CAN', 'CLIB_STRTOK_R', 'SG_DEMO_WATCH', 'DLL_FREERTOS'])
('Configs:', {'_BITS_PTHREADTYPES_H': '1', 'MINGW_GCC_PATH': 'c:/MinGW/bin', 'PYTHON2_PATH': 'c:/Python27', 'OS_PTHREAD_NUM': '32', 'OS_PTHREAD_PRIORITY': '32', 'MSYS2_GCC_PATH': 'c:/msys64/mingw64/bin', 'PYTHON3_PATH': 'c:/Anaconda3', 'ARCH': 'versatilepb', '__sigset_t_defined': '1'})
Python 3.6.4 :: Anaconda, Inc.
Python 2.7.14
Python 2.7.14
0.29.2
gcc (Rev1, Built by MSYS2 project) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

scons: done reading SConscript files.
scons: Building targets ...
CC app\app.c
arm-none-eabi-gcc: error: /Fobuildversatilepbappapp.obj: No such file or directory
arm-none-eabi-gcc: error: /c: No such file or directory
arm-none-eabi-gcc: error: appapp.c: No such file or directory
arm-none-eabi-gcc: error: /nologo: No such file or directory
arm-none-eabi-gcc: error: /DconfigTOTAL_HEAP_SIZE=0x800000: No such file or directory
arm-none-eabi-gcc: error: /DMEMORY_SIZE=0x8000000: No such file or directory
arm-none-eabi-gcc: error: /DSYSTEM_REGION_START=0x10000000: No such file or directory
arm-none-eabi-gcc: error: /DSYSTEM_REGION_END=0x101f4000: No such file or directory
arm-none-eabi-gcc: error: /DPAGE_SIZE=0x1000: No such file or directory
arm-none-eabi-gcc: error: /DOS_TICKS_PER_SECOND=100: No such file or directory
arm-none-eabi-gcc: error: /DUSECONDS_PER_TICK=10000: No such file or directory
arm-none-eabi-gcc: error: /DOS_STK_SIZE_SCALER=4: No such file or directory
arm-none-eabi-gcc: error: /DCAN_LL_DL=64: No such file or directory
arm-none-eabi-gcc: error: /DUSE_PCAPIF: No such file or directory
arm-none-eabi-gcc: error: /DUSE_PROTOTHREAD: No such file or directory
arm-none-eabi-gcc: error: /DUSE_GUI: No such file or directory
arm-none-eabi-gcc: error: /DFTPD_DEBUG: No such file or directory
arm-none-eabi-gcc: error: /DCONFIG_USE_DEFAULT_CFG: No such file or directory
arm-none-eabi-gcc: error: /DCONFIG_HAVE_OWN_OFLAGS=0: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.applicationboard.posixcommon: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.applicationcommonconfig: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructureinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurearchversatilepbbsp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurearchversatilepbmcal: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurearchcommonlwip: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationCanTp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationCom: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationComM: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationDoIP: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationNm: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationOsekNm: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationPci: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationPduR: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationSoAd: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationXcp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationJ1939Tp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurediagnosticDcm: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurememoryEa: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernel: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelaskarinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelaskarkernel: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelaskarportablearm: No such file or directory
arm-none-eabi-gcc: error: /IF:workasreleasedownloadcontikicore: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelcontikiinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelcontikiplatformnative: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemEcuM: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemSchM: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemgui: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemnetlwiplwipsrcinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemnetlwiplwipsrcincludeipv4: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemnetftp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfsfatfsfatfssource: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslwext4lwext4include: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslibelfinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslibelf: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfsvfs: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslibdl: No such file or directory
arm-none-eabi-gcc: error: /Ibuildversatilepbconfig: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomconfig: No such file or directory
arm-none-eabi-gcc: fatal error: no input files
compilation terminated.
scons: *** [build\versatilepb\app\app.obj] Error 1
scons: building terminated because of errors.

F:\work\as\release\ascore>scons
scons: Reading SConscript files ...
('Modules:', ['PLATFORM_MSYS2', 'ARCH_VERSATILEPB', 'TEST', 'PCI', 'CAN', 'FATFS_DRV', 'LWEXT4_DRV', 'EEP', 'FLS', 'LCD', 'MCU', 'LWIP_DRV', 'CANIF', 'CANNM', 'CANSM', 'CANTP', 'COM', 'COMM', 'DOIP', 'NM', 'OSEKNM', 'PDUR', 'SOAD', 'XCP', 'J1939TP', 'DCM', 'DEM', 'DET', 'EA', 'FEE', 'MEMIF', 'NVM', 'CRC', 'ECUM', 'SG', 'SCHM', 'SHELL', 'FATFS', 'LWEXT4', 'VFS', 'LIBELF', 'LIBDL', 'DEFAULT_ASKAR', 'ASKAR', 'PROTOTHREAD', 'SCHED_BUBBLE', 'PTHREAD', 'PTHREAD_SIGNAL', 'PTHREAD_CLEANUP', 'LWIP', 'LWIP_OSEK_ARCH', 'FTP', 'CLIB_ASHEAP', 'CLIB_MBOX', 'CLIB_MISCLIB',
'CLIB_QSORT', 'CLIB_STDIO_PRINTF', 'CLIB_STDIO_CAN', 'CLIB_STRTOK_R', 'SG_DEMO_WATCH', 'DLL_FREERTOS'])
('Configs:', {'_BITS_PTHREADTYPES_H': '1', 'MINGW_GCC_PATH': 'c:/MinGW/bin', 'PYTHON2_PATH': 'c:/Python27', 'OS_PTHREAD_NUM': '32', 'OS_PTHREAD_PRIORITY': '32', 'MSYS2_GCC_PATH': 'c:/msys64/mingw64/bin', 'PYTHON3_PATH': 'c:/Anaconda3', 'ARCH': 'versatilepb', '__sigset_t_defined': '1'})
Python 3.6.4 :: Anaconda, Inc.
Python 2.7.14
Python 2.7.14
0.29.2
gcc (Rev1, Built by MSYS2 project) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

scons: done reading SConscript files.
scons: Building targets ...
CC app\app.c
arm-none-eabi-gcc: error: /Foappapp.obj: No such file or directory
arm-none-eabi-gcc: error: /c: No such file or directory
arm-none-eabi-gcc: error: appapp.c: No such file or directory
arm-none-eabi-gcc: error: /nologo: No such file or directory
arm-none-eabi-gcc: error: /DconfigTOTAL_HEAP_SIZE=0x800000: No such file or directory
arm-none-eabi-gcc: error: /DMEMORY_SIZE=0x8000000: No such file or directory
arm-none-eabi-gcc: error: /DSYSTEM_REGION_START=0x10000000: No such file or directory
arm-none-eabi-gcc: error: /DSYSTEM_REGION_END=0x101f4000: No such file or directory
arm-none-eabi-gcc: error: /DPAGE_SIZE=0x1000: No such file or directory
arm-none-eabi-gcc: error: /DOS_TICKS_PER_SECOND=100: No such file or directory
arm-none-eabi-gcc: error: /DUSECONDS_PER_TICK=10000: No such file or directory
arm-none-eabi-gcc: error: /DOS_STK_SIZE_SCALER=4: No such file or directory
arm-none-eabi-gcc: error: /DCAN_LL_DL=64: No such file or directory
arm-none-eabi-gcc: error: /DUSE_PCAPIF: No such file or directory
arm-none-eabi-gcc: error: /DUSE_PROTOTHREAD: No such file or directory
arm-none-eabi-gcc: error: /DUSE_GUI: No such file or directory
arm-none-eabi-gcc: error: /DFTPD_DEBUG: No such file or directory
arm-none-eabi-gcc: error: /DCONFIG_USE_DEFAULT_CFG: No such file or directory
arm-none-eabi-gcc: error: /DCONFIG_HAVE_OWN_OFLAGS=0: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.applicationboard.posixcommon: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.applicationcommonconfig: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructureinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurearchversatilepbbsp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurearchversatilepbmcal: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurearchcommonlwip: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationCanTp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationCom: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationComM: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationDoIP: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationNm: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationOsekNm: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationPci: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationPduR: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationSoAd: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationXcp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurecommunicationJ1939Tp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurediagnosticDcm: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructurememoryEa: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernel: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelaskarinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelaskarkernel: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelaskarportablearm: No such file or directory
arm-none-eabi-gcc: error: /IF:workasreleasedownloadcontikicore: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelcontikiinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemkernelcontikiplatformnative: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemEcuM: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemSchM: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemgui: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemnetlwiplwipsrcinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemnetlwiplwipsrcincludeipv4: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemnetftp: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfsfatfsfatfssource: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslwext4lwext4include: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslibelfinclude: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslibelf: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfsvfs: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomas.infrastructuresystemfslibdl: No such file or directory
arm-none-eabi-gcc: error: /Ibuildversatilepbconfig: No such file or directory
arm-none-eabi-gcc: error: /IF:workascomconfig: No such file or directory
arm-none-eabi-gcc: fatal error: no input files
compilation terminated.
scons: *** [app\app.obj] Error 1
scons: building terminated because of errors.

F:\work\as\release\ascore>

**Comment by parai** [comment]
I think you ignore my notes in the wiki page that you need to install mingw as scons doesn't support msys2, by default it generta command according to MSVC compiler format, install mingw will solve this issue

**Comment by parai** [comment]
hi with this patch https://github.com/parai/as/commit/61d313fe2259b7a80e8495e49a3fa1f7a336820b, all issues above fixed, please update code to latest and install scons for anaconda3 as now drop the support of python27, now only anaconda3.

http://parai.github.io/as/autosar/2018/02/20/as-study-platform.html
