### ISSUE TITLE
when i input the command 'scons studio ', encounter errors

### ISSUE THREAD

**Issue by YelaShady** [parai/as#8]
Hi, parai
    after i run the console.bat and input the command 'scons studio', i encounter such errors as:
build on b'MSYS_NT-6.1', default assume 64 bit machine
'c:/msys64/mingw64/bin/pkg-config' is not recognized as an internal or external command,
operable program or batch file.
Exception: no pkg-config installed, fix the path maybe!:
so do you have any idea about such error?

**Comment by parai** [comment]
please follow http://parai.github.io/as/autosar/2018/02/20/as-study-platform.html to install all the necessay dependence, If still not working, you need to check with google why pkg-config is not installed along with gtk.

**Comment by parai** [comment]
or try install it with command "pacman -S pkg-config"

**Comment by YelaShady** [comment]
Thanks a lot, i have solved this issue.But another issue raised  when i run the command "scons studio":
The system cannot find the path specified.
Exception: FAIL of RunCommand "mklink D:\09-GitHub
\as-master\release\download\lwip-contrib\ports\win32\lwipcfg_msvc.h.
I set the "posix" to "BOARD".It seems that I lost the files of "lwip-contrip".
Because my network is terrible, I can't download all these environment config files by the bat of "Console.bat".So I download there files by searching the software-needed on the internet .
I read the file "Console.bat", but I think there are no commands to download these "lwip-contrip" files.
So How to get these files?Or do I miss some step?
