### ISSUE TITLE
link error with _sbrk, _read etc..

### ISSUE THREAD

**Issue by yifengling0** [parai/as#9]
compile with _sbrk, _read undefined error.
i add compile option with "--specs=nosys.specs'"  in building.py but still got the same error.

i think link the libnosys.a with fix the problem . but i don't know how to do.

**Comment by parai** [comment]
hi
Please check this file https://github.com/parai/as/blob/master/release/ascore/app/app.c, at the end of it, change the "#if 0" to "#if 1" to fix the build issues, and then from the out map file to check which API resulting the link of  _sbrk, _read, and then please fix that API calling by another API

**Comment by yifengling0** [comment]
ok.  change #if 0 -> 1 fixed problem。
